name: news_feeds_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  shared_preferences: ^2.2.0
  simple_animations: ^4.2.0
  supercharged: ^2.1.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Expo
      fonts:
        - asset: assets/fonts/Expo-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Expo-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Expo-Arabic-regular.ttf
          weight: 400
        - asset: assets/fonts/Expo-Arabic-Light.ttf
          weight: 300
